### ISSUE TITLE
`ToJava` and `FromJava` traits defined in jni crates

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe-client-libs#1031]
Currently our jni crates define these two traits, despite the traits being referred to in `ffi_utils` by macros in the `java.rs` module. This means that `ffi_utils` assumes that these traits exist in crates that depend on it.

Comment from @nbaksalyar from [here](https://github.com/maidsafe/ffi_utils/pull/27#discussion_r321328167):

> This part is a bit tricky.
> 
> Despite this crate being technically separate from SCL, we can't move `ToJava` and `FromJava` traits from the JNI crates as such because they rely on the bindgen which generates `ToJava` impls for types from `safe_app` or `safe_core`. So if we move these traits here, it becomes something that the compiler would prohibit: implementing imported traits for imported structs.
> 
> I see several ways of resolving this problem:
> 
> 1. Merge `safe_app_jni` into `safe_app` and `safe_authenticator_jni` into `safe_authenticator` respectively. This would require some work and would result in needing to build a separate version of `safe_app` providing the JNI functions.
> 
> 2. Have a `#[derive(ToJava, FromJava)]` procedural macro which would generate `ToJava` and `FromJava` implementations within safe_app/safe_auth (the best scenario, in my opinion).
> 
> 
> I think both of these options require considerable amount of time and task scoping, so I think it's better to handle this problem at a later time and leave the current implementation as it is.

**Comment by m-cat** [comment]
My thoughts:

1. Merging `safe_app_jni` into `safe_app` etc. makes sense with our current strategy where we have e.g. the SAFE App FFI implemented as a module in SAFE App. However, we currently are doing some internal thinkings about moving FFI into a sub-crate, e.g. `safe_app_ffi`. I'm not inclined towards this, though, and `jni` can easily be a feature-gated module in SAFE App. Would we be able to implement traits from `ffi_utils` in `safe_app_jni` for structs found elsewhere in SAFE App?

2. A custom derive also sounds good to me. It would take a bit more time than option 1, but it still seems quite simple to me. Ideally, this derive would only work with the `bindings` feature turned on, so that we do not have to pull in unnecessary dependencies during a normal build.

**Comment by ravinderjangra** [comment]
Closing this issue as the FFI layer has been moved to the `safe-api` repo and doesn't expose low-level APIs for now.
