### ISSUE TITLE
Move FFI-only error codes to an FFI-compatible enum

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe-client-libs#1097]
As of PR https://github.com/maidsafe/safe_client_libs/pull/1068, the `safe_authenticator` and `safe_app` error codes, and shared error codes from `safe_core`, are all FFI-only. We can avoid issues on the Rust side, such as inadvertently defining two constants with the same value, while still providing FFI-safe values by using FFI-compatible enums instead of manually enumerating the values. See Issue https://github.com/maidsafe/safe_client_libs/issues/967 for more information.

**Comment by ravinderjangra** [comment]
Closing this issue as the FFI layer has been moved to the `safe-api` repo.
