### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe-client-libs#1251]
1. The wiki says "See docs". It should have a link to the docs.
2. I clicked on the "docs" badge from the README ([here](https://docs.rs/safe_core/0.43.0/safe_core/)) and it has a link back to the wiki. It should also link to the docs.

**Comment by Yoga07** [comment]
Hey @m-cat, 

Not sure what you mean, but the "docs" badge in README point to `https://docs.rs/safe_core/0.43.0/safe_core/` rightly. As you can see, while the repo itself has went through a lot of changes and cut-downs to make it light weight, it has also largely moved away from the older docs in the wiki as well and had to be removed. We've decided in having the documentations at `docs.rs` by baking them right into the code via `cargo doc` with doctests and are in the process of updating it currently. Therefore with the next release, we would be linking it and be updating the README and the Wiki to reflect these new changes. Thanks for your concern! :)

**Comment by m-cat** [comment]
> it has also largely moved away from the older docs in the wiki as well and had to be removed. 

Does this mean that none of those docs are relevant anymore? I find this rather surprising. I put a lot of effort into making them accurate and thorough. Now I can't find them anywhere, which is a shame.

**Comment by Yoga07** [comment]
> Does this mean that none of those docs are relevant anymore?

For now yes, but we've got `Authenticator` coming in the future as standalone application probably and `App` also to be set up with the new Client, and those docs might come back useful. Our QA have also taken backups of all the docs before taking them down as well.

**Comment by m-cat** [comment]
Thanks for the answer @Yoga07. Looks like a lot has changed in SCL!
