### ISSUE TITLE
Update FFI for new Mutable Data types

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe-client-libs#818]
The FFI API should reflect changes made in the Mutable Data types, specifically the difference between sequenced and unsequenced types.

At this moment, it is desirable to reuse as many of existing MD APIs as possible (to retain the API familiar to app developers and make the changes on the front-end minimal). Because of this we'll be extending the MD API rather than changing it. The existing API will be related to the `Sequenced` kind of MutableData.

The changes in the API are:
* `safe_app::ffi::mutable_data::entry_actions` module:
    * All functions remain the same. `entry_version` arguments are ignored for unsequenced MutableData.
* `safe_app::ffi::mutable_data::entry_actions` module:
    * Remains intact.
* `safe_app::ffi::mutable_data` module:
    * `mdata_put` function: should multiplex based on `MDataInfo` argument and create either `UnsequencedMutableData` or `SequencedMutableData` depending on the kind of MD (see #814).
    * `mdata_get_version` function: should multiplex based on `MDataInfo` argument and send version number request for either `UnsequencedMutableData` or `SequencedMutableData` depending on the kind of MD (see #814).
    * Same for `mdata_serialised_size`.
    * `mdata_get_value` should behave the same but return `0` for `version` if requesting values from an unsequenced MutableData object.
    * `mdata_entries` should behave the same, multiplexing based on the `MDataInfo` parameter.
    * `mdata_list_keys` should behave the same, multiplexing based on the `MDataInfo` parameter.
    * `mdata_list_values` should behave the same but return `0` for `version` in `MDataValue` struct if requesting values from an unsequenced MutableData object.
    * `mdata_mutate_entries` should behave the same, determining which mutation request to send based on the `MDataInfo` parameter.
    * `mdata_list_permissions`, `mdata_list_user_permissions`, `mdata_set_user_permissions`, and `mdata_del_user_permissions` should behave the same, determining which request to send based on the `MDataInfo` parameter.
    * Implement new `mdata_delete` function with the following signature:
```rust
#[no_mangle]
pub unsafe extern "C" fn mdata_delete(
    app: *const App,
    info: *const MDataInfo,
    user_data: *mut c_void,
    o_cb: extern "C" fn(user_data: *mut c_void, result: *const FfiResult),
)
```

**Comment by ravinderjangra** [comment]
Closing this issue as the FFI layer has been moved to the `safe-api` repo and doesn't expose low-level APIs for now.
