### ISSUE TITLE
Remove `OPEN_MODE_*` constants in favor of an enum

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe-client-libs#967]
We have manually-enumerated `OPEN_MODE_*` constants in `ffi/nfs.rs` that we perform bitwise operations on, for example:

```rust
            let writer = if open_mode & (OPEN_MODE_OVERWRITE | OPEN_MODE_APPEND) != 0 {
                let writer_mode = if open_mode & OPEN_MODE_APPEND != 0 {
```

This is not idiomatic Rust: we should be using `match` and `if let` instead.

We should change these constants into an FFI-compatible enum:

```rust
#[repr(C)]
pub enum OpenMode {
    Overwrite = 1,
    Append = 2,
    Read = 4,
}
```

While we're at it, we should explicitly define integer values for the `Repr(C)` `Permission` enum in `safe_core::ipc::req::mod.rs`, enabling C users to perform bitwise operations on its variants:

```rust
/// Permission enum - use for internal storage only.
#[repr(C)]
#[derive(Copy, Clone, Debug, Eq, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
pub enum Permission {
    /// Read.
    Read = 1,
    /// Insert.
    Insert = 2,
    /// Update.
    Update = 4,
    /// Delete.
    Delete = 8,
    /// Modify permissions.
    ManagePermissions = 16,
}
```

**Comment by m-cat** [comment]
Note that the change to the `Permission` struct is not necessary as it should be [removed entirely](https://github.com/maidsafe/safe_client_libs/issues/971).

**Comment by ravinderjangra** [comment]
Closing this issue as the FFI layer has been moved to the `safe-api` repo and doesn't expose low-level APIs for now.
