### ISSUE TITLE
Consider using `extern "C"` block in FFI

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe-client-libs#968]
Instead of writing our FFI functions like this:

```rust
#[no_mangle]
pub unsafe extern "C" fn function_1() {...}

#[no_mangle]
pub unsafe extern "C" fn function_2() {...}

fn helper() {...}
```

We can enclose them in a block like this:

```rust
extern "C" {
    #[no_mangle]
    pub unsafe fn function_1() {...}

    #[no_mangle]
    pub unsafe fn function_2() {...}
}

fn helper() {...}
```

As well as being less verbose, this would have the advantage of organizing and separating the strictly-FFI functions from Rust-only helper functions.

**Comment by hunterlester** [comment]
@m-cat Looking into picking this up to get back into contribution in my spare time.
Looks though like I may be doubling the work if I were to refactor before #818 is completed.
Let me know your thoughts.
Have you already started #818?

**Comment by m-cat** [comment]
Hey @hunterlester, that's great!

We haven't started working on FFI and don't have any plans to do so for the time being. Feel free to pick this up, and let me know if you have any questions.

**Comment by ravinderjangra** [comment]
The FFI layer has been moved to the `safe-api` repo and these refactorning changes can be made there.
